language: node_js

node_js:
    - "7.5.0"

services: mongodb

env:
    global:
        - CHROME_BIN="chromium-browser"
        - CXX=g++-4.8
        - DISPLAY=:99.0
        - NODE_ENV=test

dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

cache:
    directories:
        - node_modules

before_script:
    - cp ./config/test-dist.js ./config/test.js

before_install:
    - sh -e /etc/init.d/xvfb start
    - sleep 3

install:
    - "make --silent install"

script: make test
