server:
    image: node:7.5.0
    volumes:
        - ./api:/app:Z
    links:
        - mongo
    working_dir: /app
    ports:
        - 3000:3000
    command: npm run dev
    user: "${UID}:${GID}"

mongo:
    image: mongo:3.0.14
    ports:
        - 27017:27017

frontend:
    image: node:7.5.0
    volumes:
        - ./frontend:/app:Z
    working_dir: /app
    ports:
        - 8080:8080
    command: npm run dev
    user: "${UID}:${GID}"
