server:
    image: node:7.5.0
    volumes:
        - ./api:/app:Z
    links:
        - postgres
    working_dir: /app
    ports:
        - 3000:3000
    command: npm run dev
    user: "${UID}:${GID}"

postgres:
    image: postgres:9.6.2
    ports:
        - 5432:5432

frontend:
    image: node:7.5.0
    volumes:
        - ./frontend:/app:Z
    working_dir: /app
    ports:
        - 8080:8080
    command: npm run dev
    user: "${UID}:${GID}"
